# Generated by Django 6.0.7 on 2026-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Pokhara', 'Pokhara'), ('Chitwan', 'Chitwan'), ('Biratnagar', 'Biratnagar'), ('Birgunj', 'Birgunj'), ('Dharan', 'Dharan'), ('Butwal', 'Butwal'), ('Nepalgunj', 'Nepalgunj'), ('Other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_hours', models.CharField(default='24/7 Emergency Service', max_length=100)),
                ('is_24_hours', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='donations_count',
            field=models.IntegerField(default=0, help_text='Total verified blood donations'),
        ),
    ]
